### ISSUE TITLE
Filtering in My activities in Dashboard only shows Save

### ISSUE THREAD

**Issue by jupouta** [Transkribus/TWI-mc#18] opened 2017-06-15 12:51 UTC
Dashboard --> My activities: filtering according to anything

Filtering only shows the _Operation_ **Save** in _My activities_ table (although filtered with Access Document for instance) and apparently doesn't do that correctly either.
It seems not to work on any browser.

**Comment by cziaarm** [comment] 2017-06-19 19:12
duplicate of Transkribus/TWI-dashboard#17

**Closed as completed** 2017-06-28 12:41 UTC
Labels: bug, duplicate
